
title: Bristol Open Data
tagline: Helping people in and around Bristol make use of open data
locale: en_GB
description: Helping Bristol to use more and share more open data. We also run the Bristol ODI Node.
logo: site-logo.png
search: true
url: https://bristolopendata.github.io

# Jekyll configuration

permalink:   /:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false


# Site owner
owner:
  name: Bristol Open Data
  avatar: bio-photo.jpg
  email: bod@gmail.com
  disqus-shortname:
  twitter: BristolOpenData
  meetup: Bristol_Open_Data
  facebook: #username
  github: #BristolOpenData
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify: